### ISSUE TITLE
Create releases and provide pre-built binaries

### ISSUE THREAD

**Issue by siddhantac** [siddhantac/puffin#2]

**Comment by phobo3s** [comment]
in the future will it be runnable on windows?

**Comment by siddhantac** [comment]
Yes, I will try to make it available on windows. :) Thank you for your interest in this project.

**Comment by santagoy** [comment]
I'm excited to see where this goes!

**Comment by siddhantac** [comment]
It is runnable on windows! But might need some tweaking with latest version of hledger.
