### ISSUE TITLE
reporting with -V option

### ISSUE THREAD

**Issue by phobo3s** [siddhantac/puffin#42]
it will be perfect if it could use the -V option in hledger. That way you can check all your investments.

**Comment by siddhantac** [comment]
Thanks for the suggestion! 

I haven't added anything related to investments yet, but this might be a good place to start. Could you provide a sample journal file that can be used for development and testing?

**Comment by phobo3s** [comment]
[Main_.txt](https://github.com/user-attachments/files/16056172/Main_.txt)
i think this can work.

**Comment by siddhantac** [comment]
You can now add custom options :)

**Comment by phobo3s** [comment]
how can i use custom options?

**Comment by siddhantac** [comment]
You can use custom options by using 

```shell
puffin -cfg config.json
```

And in the config.json file, you can setup your own reports. 

Based on your comment in the other issue, I assume you have already figured out this part. :)

**Comment by phobo3s** [comment]
yes. sorry to bother. i figured out like you said :)
