### ISSUE TITLE
integrated price fetching unit. 

### ISSUE THREAD

**Issue by phobo3s** [siddhantac/puffin#47]
i don't know if this is in the scope of the project but there can be a price fetching script and csv database for hledger. 
i am not a programmer like you are but;
https://github.com/phobo3s/PriceFetcher

**Comment by siddhantac** [comment]
Could you please provide some more context and information? Thank you

**Comment by phobo3s** [comment]
oh. i am very very sorry for confusion. i mus have closed the window. i am editing rigth away.

**Comment by siddhantac** [comment]
This might be out of scope for this project, sorry. I may consider it as a future enhancement.
