### ISSUE TITLE
Config File accounts

### ISSUE THREAD

**Issue by phobo3s** [siddhantac/puffin#52]
hello, 
i am trying to use new config file support this is my config file

```
{
    "startDate": "2024",
    "period": "yearly",
    "reports": [
        {
            "name": "balance sheet",
            "cmd": "hledger balancesheet -V -R -4 "
        },
        {
            "name": "Varlıklar",
            "cmd": "hledger balance type:a -V "
        },
        {
            "name": "Yükümlülükler",
            "cmd": "hledger balance type:l "
        },
        {
            "name": "Gelir",
            "cmd": "hledger balance type:r "
        },
        {
            "name": "Gider",
            "cmd": "hledger balance type:x -M -p 2024",
            "locked": true
        },
        {
            "name": "Gelir Tablosu",
            "cmd": "hledger incomestatement "
        },
        {
            "name": "accounts",
            "cmd": "hledger accounts",
            "locked": true
        },
	{
            "name": "printer",
            "cmd": "hledger print "
        }
    ]
}
```
the accounts tab gives error "hledger: error: unknown flag: --layout (exit status 1)
 one more thing;
with this config file the table named "Gider" is shown like this
![image](https://github.com/user-attachments/assets/3aee0416-c2c3-459a-ae75-14d2baba60d1)

as you can see i give command "cmd": "hledger balance type:x -M -p 2024",
but this result is not monthly

**Comment by wllfaria** [comment]
Out of curiosity I've investigated this a little, so @siddhantac, [here](https://github.com/siddhantac/puffin/blob/503351837387ce99983fa668181fa29140fdd0bc/ui/model.go#L55) where all the pagers are built, `runCommand` is called, and from what I've investigated, just happens that this closure [here](https://github.com/siddhantac/puffin/blob/503351837387ce99983fa668181fa29140fdd0bc/ui/command.go#L11) 

```go
func runCommand(cmd string) func(options hledger.Options) string {
	return func(options hledger.Options) string {
		buf, err := accounting.RunCommand(cmd, options)
		if err != nil {
			return err.Error()
		}
		b, err := io.ReadAll(buf)
		if err != nil {
			return err.Error()
		}
		return string(b)
	}
}
```

always have the options previously defined by other commands, which includes `--layout bare` which is not supported on the command "accounts".

hopefully this helps you a little

**Comment by siddhantac** [comment]
@phobo3s thank you for the bug report!

@wllfaria thank you for the investigation!

I'll fix this soon.
