### ISSUE TITLE
Cannot get out of help menu

### ISSUE THREAD

**Issue by Askath** [siddhantac/puffin#62]
I just build new the current version 2.1 and noticed that after pressing '?' and seeing the keybindings, I cannot get back to the main screen. 

Not sure if there is a keybind I am missing or if I messed something else up. 
 
 
<img width="973" alt="image" src="https://github.com/user-attachments/assets/522a2e98-c2a5-4bf9-872e-c1ddd900aa8b">

**Comment by siddhantac** [comment]
It should go back to the app when you press `?` again. Can you try that?

**Comment by Askath** [comment]
> It should go back to the default view when you press `?` again. Can you try that?

Does not seem to work sadly. Tried with both macos Stock Terminal and iTerm.

**Comment by Askath** [comment]
Looks like other keys like 'q' or 'ctrl+c" also dont work as if the whole tool is unresponsive

**Comment by siddhantac** [comment]
Interesting. Obviously "it works for me", lol. 

If you'd be willing to help with this issue, I can add some more debugging information so that you can run it in debug mode to collect more data. 🙂

**Comment by Askath** [comment]
> Interesting. Thanks for reporting it. Obviously "it works for me", lol.
> 
> If you'd be willing to help with this issue, I can add some more debugging information so that you can run it in debug mode to collect more data. 🙂

sure! I'd be happy to help. Love this tool, already makes life a lot easier. I am just not as proficient in go/bubbletea.

**Comment by siddhantac** [comment]
> sure! I'd be happy to help. Love this tool, already makes life a lot easier.

Thank you! Glad it's helping you.

> I am just not as proficient in go/bubbletea.

That's fine! I would just need you to send me the log file later.

I'll add some targeted debug logs. Give me a few days, I'll let you know once it's ready.

**Comment by Askath** [comment]
> > sure! I'd be happy to help. Love this tool, already makes life a lot easier.
> 
> Thank you! Glad it's helping you.
> 
> > I am just not as proficient in go/bubbletea.
> 
> That's fine! I would just need you to send me the log file later.
> 
> I'll add some targeted debug logs. Give me a few days, I'll let you know once it's ready.

No problem! Thanks for your work

**Comment by siddhantac** [comment]
Hi @Askath, could you please pull the latest commit from this branch: https://github.com/siddhantac/puffin/tree/better-debug

You can run the debug version in 2 ways:
1. `make debug` - this is the simplest. It will run puffin in debug mode and it will use the `config.debug.json` file (which uses test journal data)
2. `make build && ./puffin -debug -cfg config.debug.json` this will build the binary and then run it in debug mode.

Both methods are equivalent, and it doesn't really matter which one you pick :)

The debug log will be written to `puffin.log`. Once you have run the program, please paste the output of the file here. I have tried my best to not log any financial data, but please do verify that there is no financial data before submitting the file. You may also use the test journal data in the repo.

Once the program is running, please press the help key at least twice (`?`) so that we can see what's happening after the help view is displayed. You can also press a few other keys to see if they get logged.

And finally, please let me know which platform you are running it on!

**Comment by Askath** [comment]
Will do when I am done with work later this day

**Comment by Askath** [comment]
Eh okay quiet day at work. Here is the log. 
I am using mac os m3 and on the standard Terminal.app or using iTerm. Shell I am using is the fish shell although I have also tried it in bash.

`debug 2024/09/11 09:39:07 init puffin v2.1.0
debug 2024/09/11 09:39:08 root: showing main view
debug 2024/09/11 09:39:08 root: msg: tea.WindowSizeMsg, {231 60}
debug 2024/09/11 09:39:08 register(0): tableSize: w=216, h=54
debug 2024/09/11 09:39:09 root: windowSizeMsg: full: h=60, w=231. mainView: h=58, w=219
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 root: msg: tea.KeyMsg, alt+]
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 root: msg: tea.sequenceMsg, [0x100416400 0x10041f520]
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 root: msg: spinner.TickMsg, {2024-09-11 09:39:09.636434 +0200 CEST m=+1.808768834 0 1}
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 root: msg: tea.enterAltScreenMsg, {}
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 root: msg: tea.KeyMsg, 11;rgb:0000/0000/0000
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 root: msg: ui.modelLoading, {}
debug 2024/09/11 09:39:09 register(0): unready
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 root: msg: tea.KeyMsg, alt+\
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 cmd: [hledger register -f data/hledger.journal --depth=3 date:2021.. -O csv]
debug 2024/09/11 09:39:09 root: msg: spinner.TickMsg, {2024-09-11 09:39:09.780337184 +0200 CEST m=+1.952670685 1 1}
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 root: msg: ui.content
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 root: msg: spinner.TickMsg, {2024-09-11 09:39:09.924404517 +0200 CEST m=+2.096737060 2 1}
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:13 root: msg: tea.KeyMsg, ?
debug 2024/09/11 09:39:13 help: true
debug 2024/09/11 09:39:13 root: showing help
debug 2024/09/11 09:39:24 root: msg: tea.KeyMsg, 11;rgb:0000/0000/0000
debug 2024/09/11 09:39:24 root: showing help
debug 2024/09/11 09:39:27 root: msg: tea.KeyMsg, alt+\
debug 2024/09/11 09:39:27 root: showing help
debug 2024/09/11 09:39:29 root: msg: tea.KeyMsg, ]11;rgb:0000/0000/0000
debug 2024/09/11 09:39:29 root: showing help
debug 2024/09/11 09:39:31 root: msg: tea.KeyMsg, alt+\
debug 2024/09/11 09:39:31 root: showing help
debug 2024/09/11 09:39:35 root: msg: tea.KeyMsg, ]11;rgb:0000/0000/0000
debug 2024/09/11 09:39:35 root: showing help
debug 2024/09/11 09:39:42 root: msg: tea.WindowSizeMsg, {231 59}
debug 2024/09/11 09:39:42 register(0): tableSize: w=216, h=53
debug 2024/09/11 09:39:45 root: windowSizeMsg: full: h=59, w=231. mainView: h=57, w=219
debug 2024/09/11 09:39:45 root: showing help
debug 2024/09/11 09:39:53 root: msg: tea.KeyMsg, alt+\
debug 2024/09/11 09:39:53 root: showing help
debug 2024/09/11 09:40:01 root: msg: tea.sequenceMsg, [0x100416400 0x10041f520]
debug 2024/09/11 09:40:01 root: showing help
debug 2024/09/11 09:40:08 root: msg: tea.KeyMsg, ]11;rgb:0000/0000/0000
debug 2024/09/11 09:40:08 root: showing help
debug 2024/09/11 09:40:16 root: msg: ui.modelLoading, {}
debug 2024/09/11 09:40:16 register(0): unready
debug 2024/09/11 09:40:16 root: showing help
debug 2024/09/11 09:40:16 cmd: [hledger register -f data/hledger.journal --depth=3 date:2021.. -O csv]
debug 2024/09/11 09:40:23 root: msg: tea.KeyMsg, alt+\
debug 2024/09/11 09:40:23 root: showing help
debug 2024/09/11 09:40:36 root: msg: ui.content
debug 2024/09/11 09:40:36 root: showing help
debug 2024/09/11 09:40:43 root: msg: tea.KeyMsg, 000/0000/0000
debug 2024/09/11 09:40:43 root: showing help
`

**Comment by Askath** [comment]
Okay here is the log, had some more time. I am using an mac pro m3, using Terminal.app and iterm emulator. 
Shell I am using is fish but I also tried it in bash.

debug 2024/09/11 09:39:07 init puffin v2.1.0
debug 2024/09/11 09:39:08 root: showing main view
debug 2024/09/11 09:39:08 root: msg: tea.WindowSizeMsg, {231 60}
debug 2024/09/11 09:39:08 register(0): tableSize: w=216, h=54
debug 2024/09/11 09:39:09 root: windowSizeMsg: full: h=60, w=231. mainView: h=58, w=219
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 root: msg: tea.KeyMsg, alt+]
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 root: msg: tea.sequenceMsg, [0x100416400 0x10041f520]
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 root: msg: spinner.TickMsg, {2024-09-11 09:39:09.636434 +0200 CEST m=+1.808768834 0 1}
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 root: msg: tea.enterAltScreenMsg, {}
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 root: msg: tea.KeyMsg, 11;rgb:0000/0000/0000
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 root: msg: ui.modelLoading, {}
debug 2024/09/11 09:39:09 register(0): unready
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 root: msg: tea.KeyMsg, alt+\
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 cmd: [hledger register -f data/hledger.journal --depth=3 date:2021.. -O csv]
debug 2024/09/11 09:39:09 root: msg: spinner.TickMsg, {2024-09-11 09:39:09.780337184 +0200 CEST m=+1.952670685 1 1}
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 root: msg: ui.content
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:09 root: msg: spinner.TickMsg, {2024-09-11 09:39:09.924404517 +0200 CEST m=+2.096737060 2 1}
debug 2024/09/11 09:39:09 root: showing main view
debug 2024/09/11 09:39:13 root: msg: tea.KeyMsg, ?
debug 2024/09/11 09:39:13 help: true
debug 2024/09/11 09:39:13 root: showing help
debug 2024/09/11 09:39:24 root: msg: tea.KeyMsg, 11;rgb:0000/0000/0000
debug 2024/09/11 09:39:24 root: showing help
debug 2024/09/11 09:39:27 root: msg: tea.KeyMsg, alt+\
debug 2024/09/11 09:39:27 root: showing help
debug 2024/09/11 09:39:29 root: msg: tea.KeyMsg, ]11;rgb:0000/0000/0000
debug 2024/09/11 09:39:29 root: showing help
debug 2024/09/11 09:39:31 root: msg: tea.KeyMsg, alt+\
debug 2024/09/11 09:39:31 root: showing help
debug 2024/09/11 09:39:35 root: msg: tea.KeyMsg, ]11;rgb:0000/0000/0000
debug 2024/09/11 09:39:35 root: showing help
debug 2024/09/11 09:39:42 root: msg: tea.WindowSizeMsg, {231 59}
debug 2024/09/11 09:39:42 register(0): tableSize: w=216, h=53
debug 2024/09/11 09:39:45 root: windowSizeMsg: full: h=59, w=231. mainView: h=57, w=219
debug 2024/09/11 09:39:45 root: showing help
debug 2024/09/11 09:39:53 root: msg: tea.KeyMsg, alt+\
debug 2024/09/11 09:39:53 root: showing help
debug 2024/09/11 09:40:01 root: msg: tea.sequenceMsg, [0x100416400 0x10041f520]
debug 2024/09/11 09:40:01 root: showing help
debug 2024/09/11 09:40:08 root: msg: tea.KeyMsg, ]11;rgb:0000/0000/0000
debug 2024/09/11 09:40:08 root: showing help
debug 2024/09/11 09:40:16 root: msg: ui.modelLoading, {}
debug 2024/09/11 09:40:16 register(0): unready
debug 2024/09/11 09:40:16 root: showing help
debug 2024/09/11 09:40:16 cmd: [hledger register -f data/hledger.journal --depth=3 date:2021.. -O csv]
debug 2024/09/11 09:40:23 root: msg: tea.KeyMsg, alt+\
debug 2024/09/11 09:40:23 root: showing help
debug 2024/09/11 09:40:36 root: msg: ui.content
debug 2024/09/11 09:40:36 root: showing help
debug 2024/09/11 09:40:43 root: msg: tea.KeyMsg, 000/0000/0000
debug 2024/09/11 09:40:43 root: showing help

**Comment by siddhantac** [comment]
There's some interesting stuff in there. Are you using some keymap modifier software or a specialty keyboard?

1. There's a bunch of `root: msg: tea.KeyMsg, alt+` . Do you know which key that represents? 
2. Near the beginning there's a `root: msg: tea.KeyMsg, alt+]` , again what does that represent? Is it `⌥ + ]` ? 
3. This log is when the help was first shown `2024/09/11 09:39:13 root: msg: tea.KeyMsg, ?`. Which makes sense. But after that there are no more `?` keypresses. 
4. There's also many keypresses with `]11;rgb` or a string of 0s which I can't explain.

**Comment by Askath** [comment]
yeah I noticed that. the alt+ is alt+ is  what happens when I press '?' in the help menu I think. 

This "debug 2024/09/11 09:40:43 root: msg: tea.KeyMsg, 000/0000/0000" could be me pressing cmd+t as I opened a new tab in the terminal to close puffin.

Let me try it with a different keyboard

**Comment by Askath** [comment]
thats the log when using the normal mac keyboard. I am more confused than before. I only open puffin, and pressed ? twice. 

debug 2024/09/11 10:33:08 init puffin v2.1.0
debug 2024/09/11 10:33:08 root: showing main view
debug 2024/09/11 10:33:08 root: msg: spinner.TickMsg, {2024-09-11 10:33:08.693842 +0200 CEST m=+0.014568168 0 1}
debug 2024/09/11 10:33:08 root: showing main view
debug 2024/09/11 10:33:08 root: msg: tea.WindowSizeMsg, {283 75}
debug 2024/09/11 10:33:08 register(0): tableSize: w=268, h=69
debug 2024/09/11 10:33:13 root: windowSizeMsg: full: h=75, w=283. mainView: h=73, w=271
debug 2024/09/11 10:33:13 root: showing main view
debug 2024/09/11 10:33:13 root: msg: tea.enterAltScreenMsg, {}
debug 2024/09/11 10:33:13 root: showing main view
debug 2024/09/11 10:33:13 root: msg: tea.KeyMsg, 11;rgb:1e1e/1e1e/1e1e
debug 2024/09/11 10:33:13 root: showing main view
debug 2024/09/11 10:33:13 root: msg: spinner.TickMsg, {2024-09-11 10:33:08.836775725 +0200 CEST m=+0.157500851 1 1}
debug 2024/09/11 10:33:13 root: showing main view
debug 2024/09/11 10:33:13 root: msg: tea.sequenceMsg, [0x102da2400 0x102dab520]
debug 2024/09/11 10:33:13 root: showing main view
debug 2024/09/11 10:33:13 root: msg: tea.KeyMsg, ctrl+g
debug 2024/09/11 10:33:13 root: showing main view
debug 2024/09/11 10:33:13 root: msg: ui.modelLoading, {}
debug 2024/09/11 10:33:13 register(0): unready
debug 2024/09/11 10:33:13 root: showing main view
debug 2024/09/11 10:33:13 cmd: [hledger register -f data/hledger.journal --depth=3 date:2021.. -O csv]
debug 2024/09/11 10:33:13 root: msg: ui.content
debug 2024/09/11 10:33:13 root: showing main view
debug 2024/09/11 10:33:13 root: msg: spinner.TickMsg, {2024-09-11 10:33:13.857200059 +0200 CEST m=+5.177911060 2 1}
debug 2024/09/11 10:33:13 root: showing main view
debug 2024/09/11 10:33:17 root: msg: tea.KeyMsg, ?
debug 2024/09/11 10:33:17 help: true
debug 2024/09/11 10:33:17 root: showing help
debug 2024/09/11 10:33:17 root: msg: tea.KeyMsg, ]11;rgb:1e1e/1e1e/1e1e
debug 2024/09/11 10:33:17 root: showing help
debug 2024/09/11 10:33:17 root: msg: tea.KeyMsg, ctrl+g
debug 2024/09/11 10:33:17 root: showing help
debug 2024/09/11 10:33:17 root: msg: tea.KeyMsg, ]11;rgb:1e1e/1e1e/1e1e
debug 2024/09/11 10:33:17 root: showing help
debug 2024/09/11 10:33:17 root: msg: tea.KeyMsg, ctrl+g
debug 2024/09/11 10:33:17 root: showing help
debug 2024/09/11 10:33:17 root: msg: tea.KeyMsg, ]11;rgb:1e1e/1e1e/1e1e
debug 2024/09/11 10:33:17 root: showing help
debug 2024/09/11 10:33:17 root: msg: tea.KeyMsg, ctrl+g
debug 2024/09/11 10:33:17 root: showing help
debug 2024/09/11 10:33:17 root: msg: tea.KeyMsg, ]11;rgb:1e1e/1e1e/1e1e
debug 2024/09/11 10:33:17 root: showing help
debug 2024/09/11 10:33:17 root: msg: tea.KeyMsg, ctrl+g
debug 2024/09/11 10:33:17 root: showing help
debug 2024/09/11 10:33:24 root: msg: tea.KeyMsg, 1;rgb:1e1e/1e1e/1e1e
debug 2024/09/11 10:33:24 root: showing help
debug 2024/09/11 10:33:24 root: msg: tea.KeyMsg, ctrl+g
debug 2024/09/11 10:33:24 root: showing help

**Comment by Askath** [comment]
found this issue in bubbletea https://github.com/charmbracelet/bubbletea/issues/1126
might have something to do with it?

**Comment by Askath** [comment]
Lowered the bubbletea version to 26.2 to try it out, and now puffin works perfect again :)

**Comment by siddhantac** [comment]
Thanks for investigating! I'll update the go.mod accordingly. :)
